import mongoose from "mongoose";
import dotenv from "dotenv";
import { Journal } from "../models/journal.model.js";
import { Product } from "../models/product.model.js"; 

dotenv.config();

const MONGO_URI = process.env.MONGODB_URI || "mongodb+srv://satyajitswain2006_db_user:PQC4J3KsTpOczhiH@cluster0.fdyhenl.mongodb.net/nirvana_republic?retryWrites=true&w=majority";

const seedJournals = [
  {
    title: "The Anatomy of Cold-Processed Moringa: Why Temperature Dictates Potency",
    slug: "anatomy-of-cold-processed-moringa",
    category: "Nutrition Notes",
    readTimeMinutes: 4,
    excerpt: "Heat destroys delicate glucosinolates and antioxidant enzymes. Here is how low-temperature shade drying preserves the vibrant emerald profile of farm-fresh drumstick leaves.",
    content: `When commercial operations accelerate dehydration using industrial ovens or direct sun exposure, the heat strips away the very compounds that make Moringa oleifera a superfood. 

Glucosinolates and vitamin C are exceptionally thermal-sensitive. At temperatures exceeding 45°C, these active molecules degrade rapidly, leaving behind a dull brown powder devoid of enzymatic life.

At Nirvana Republic, our farm partners in the southern peninsula utilize slow, shaded drying chambers with continuous gentle airflow. This meticulous process locks in chlorophyll, bioavailable iron, and high concentrations of chlorogenic acid—ensuring that every morning teaspoon delivers the uncompromised vitality intended by nature.`,
    coverImage: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80",
    tags: ["Moringa", "BotanicalScience", "ColdProcessed", "FarmDirect"],
    isPublished: true,
    publishedAt: new Date("2026-05-10"),
    author: { name: "Dr. Alok Verma", role: "Chief Botanist" },
  },
  {
    title: "Tracing the Harvest: Inside Our Certified Organic Chia Farm Clusters in Central India",
    slug: "tracing-harvest-central-india-chia",
    category: "Farm Stories",
    readTimeMinutes: 5,
    excerpt: "A photo-chronicled dispatch from the nutrient-dense black cotton soils where our raw omega-3 chia seeds are cultivated without synthetic nitrogen or chemical desiccants.",
    content: `Central India's undulating plateaus possess a unique microclimate characterized by cool winters and well-draining alluvial soils—ideal conditions for Salvia hispanica. 

Unlike imported commercial lots that undergo fumigation and prolonged transit times, our chia batches travel straight from grower cooperatives in Madhya Pradesh to our packing unit in Bengaluru. 

Each lot undergoes rigorous independent testing for heavy metals and pesticide residues. When you pour a spoonful into your morning water, you aren't just consuming fibre and ALA omega fatty acids; you are supporting regenerative farming clusters that prioritize soil health over maximum yields.`,
    coverImage: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=1200&q=80",
    tags: ["ChiaSeeds", "FarmProvenance", "RegenerativeAgriculture", "Omega3"],
    isPublished: true,
    publishedAt: new Date("2026-04-22"),
    author: { name: "Satyajit Swain", role: "Agricultural Sourcing Lead" },
  },
  {
    title: "The Two-Minute Morning Ritual: Replacing Caffeine Spikes with Sustained Cellular Energy",
    slug: "two-minute-morning-ritual-cellular-energy",
    category: "Rituals",
    readTimeMinutes: 3,
    excerpt: "How a single glass of lukewarm water infused with ceremonial seed powders establishes steady cortisol rhythms and stabilizes blood glucose before your first meal.",
    content: `Modern mornings are often a chaotic rush dominated by immediate caffeine consumption on an empty stomach—a habit that triggers an artificial cortisol spike and subsequent midday crash.

The two-minute morning ritual requires no complicated preparation or supplement schedules. Take one glass of structured or filtered room-temperature water, stir in a teaspoon of nutrient-dense greens or micronized superfoods, and consume slowly before your morning chai or coffee.

This simple pause primes gastric function, delivers bioavailable minerals, and builds an anchor of consistency that governs your daily wellbeing.`,
    coverImage: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=80",
    tags: ["DailyRituals", "MorningRoutine", "WellnessHabits", "Energy"],
    isPublished: true,
    publishedAt: new Date("2026-04-15"),
    author: { name: "Nirvana Editorial", role: "Wellness Curator" },
  },
  {
    title: "Unrefined Jaggery vs. Refined White Sugar: The Mineral Matrix Difference",
    slug: "unrefined-jaggery-vs-refined-white-sugar",
    category: "Recipes",
    readTimeMinutes: 4,
    excerpt: "Why traditional cane sweeteners packed with natural iron, magnesium, and trace molasses behave entirely differently in your metabolic pathway than bleached sucrose.",
    content: `Industrial white sugar is an isolated carbohydrate stripped of every trace mineral during centrifugation and sulfur bleaching. 

In contrast, traditional unrefined cane jaggery (Gur) retains the rich, complex mineral matrix of the original sugarcane juice. Containing natural iron, magnesium, potassium, and antioxidants, unrefined jaggery provides a slower glycemic release without robbing your body of co-factors required for carbohydrate metabolism.

Use it in your evening golden milk or herbal infusions to satisfy sweetness cravings while nourishing your cellular electrolyte balance.`,
    coverImage: "https://images.unsplash.com/photo-1587735243615-c03f25cac120?auto=format&fit=crop&w=1200&q=80",
    tags: ["Jaggery", "PantryStaples", "Unrefined", "MetabolicHealth"],
    isPublished: true,
    publishedAt: new Date("2026-03-30"),
    author: { name: "Chef Maya Rao", role: "Pantry & Kitchen Consultant" },
  },
  {
    title: "Adaptogens in Practice: Integrating Ashwagandha Root Powder into Your Evening Wind-Down",
    slug: "integrating-ashwagandha-root-powder-evening-wind-down",
    category: "Nutrition Notes",
    readTimeMinutes: 5,
    excerpt: "Examining withanolides and their neuroendocrine mechanisms in regulating the hypothalamic-pituitary-adrenal (HPA) axis for restorative, deep-stage sleep.",
    content: `Withania somnifera, commonly known as Ashwagandha, has been revered in classical botanical texts for millennia as a premier rasayana (rejuvenative herb). 

Modern clinical studies increasingly validate its role as an adaptogen—a natural substance that helps the body buffer physiological and psychological stress. The active steroidal lactones, known as withanolides, interact with GABAergic receptors to quiet an overactive nervous system.

Stirring a half-spoon of pure root powder into warm milk or almond milk with a touch of cardamom and jaggery at sunset creates the ultimate physiological cue for restorative sleep.`,
    coverImage: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
    tags: ["Ashwagandha", "Adaptogens", "SleepScience", "Ayurveda"],
    isPublished: true,
    publishedAt: new Date("2026-03-12"),
    author: { name: "Dr. Alok Verma", role: "Chief Botanist" },
  },
];

const seedProducts = [
  {
    name: "Ceremonial Grade Raw Chia Seeds",
    slug: "ceremonial-grade-raw-chia-seeds",
    category: "seeds",
    tagline: "Unblended omega-3 rich ceremonial chia seeds",
    ritualInstruction: "Stir one teaspoon into a glass of morning water before meals.",
    price: 349,
    compareAtPrice: 449,
    weightGrams: 250,
    sku: "NR-CHIA-250",
    description: "Sourced directly from central Indian black cotton soil cooperatives. Exceptionally high in alpha-linolenic omega-3 fatty acids and soluble dietary fibre.",
    images: ["https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Vidarbha Cluster",
      region: "Central Plateau",
      state: "Madhya Pradesh",
    },
    harvestPeriod: "March 2026",
    labReportRef: "NR-LAB-CHIA-092",
    ritualTiming: "Morning",
    benefits: ["Rich in Omega-3", "High Dietary Fibre", "Sustained Energy"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 486,
      protein: 16.5,
      carbohydrates: 42.1,
      dietaryFiber: 34.4,
      fat: 30.7,
    },
    isFeatured: true,
    isBestSeller: true,
    stockQuantity: 120,
  },
  {
    name: "Cold-Processed Shade-Dried Moringa Leaf Powder",
    slug: "cold-processed-moringa-leaf-powder",
    category: "powders",
    tagline: "Vibrant emerald green shade-dried drumstick leaves",
    ritualInstruction: "Mix half a spoon into warm water or green juice.",
    price: 299,
    compareAtPrice: 399,
    weightGrams: 200,
    sku: "NR-MOR-200",
    description: "Vibrant emerald green powder dehydrated under gentle shade to preserve delicate chlorophyll, bioavailable iron, and antioxidant enzymes.",
    images: ["https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Nilgiri Foothills Cluster",
      region: "Southern Ghats",
      state: "Tamil Nadu",
    },
    harvestPeriod: "April 2026",
    labReportRef: "NR-LAB-MOR-411",
    ritualTiming: "Morning",
    benefits: ["Bioavailable Iron", "Chlorophyll Rich", "Cellular Vitality"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 325,
      protein: 27.1,
      carbohydrates: 38.2,
      dietaryFiber: 19.2,
      fat: 6.5,
    },
    isFeatured: true,
    isBestSeller: true,
    stockQuantity: 95,
  },
  {
    name: "Unbleached Artisanal Palm Jaggery Cubes",
    slug: "unbleached-artisanal-palm-jaggery-cubes",
    category: "pantry",
    tagline: "Traditional single-origin palm nectar blocks",
    ritualInstruction: "Dissolve a small cube into evening herbal tea or milk.",
    price: 275,
    compareAtPrice: 350,
    weightGrams: 500,
    sku: "NR-JAG-500",
    description: "Traditional single-origin palm nectar boiled in open iron pans without chemical clarifying agents or sulfur dioxide. Rich in natural iron.",
    images: ["https://images.unsplash.com/photo-1587735243615-c03f25cac120?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Palakkad Grove",
      region: "Malabar Coast",
      state: "Kerala",
    },
    harvestPeriod: "February 2026",
    labReportRef: "NR-LAB-JAG-105",
    ritualTiming: "Night",
    benefits: ["Natural Iron Source", "Unbleached", "Slow Glycemic Release"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 383,
      protein: 0.4,
      carbohydrates: 95.0,
      dietaryFiber: 0.2,
      fat: 0.1,
    },
    isFeatured: true,
    isBestSeller: false,
    stockQuantity: 80,
  },
  {
    name: "Wild Forest Raw Honey (Multifloral)",
    slug: "wild-forest-raw-honey-multifloral",
    category: "pantry",
    tagline: "Unheated forest blossom honey packed with natural pollen",
    ritualInstruction: "Enjoy one raw spoonful directly or in lukewarm lemon water.",
    price: 549,
    compareAtPrice: 699,
    weightGrams: 400,
    sku: "NR-HON-400",
    description: "Harvested by indigenous tribal gatherers from deep forest blossoms. Unheated, unfiltered, and retaining all natural pollen grains.",
    images: ["https://images.unsplash.com/photo-1587049352847-4a222e784d38?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Western Ghats Bio-Reserve",
      region: "Sahyadri Range",
      state: "Karnataka",
    },
    harvestPeriod: "January 2026",
    labReportRef: "NR-LAB-HON-204",
    ritualTiming: "Morning",
    benefits: ["Unfiltered Pollen", "Enzyme Rich", "Immune Support"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 304,
      protein: 0.3,
      carbohydrates: 82.4,
      dietaryFiber: 0.2,
      fat: 0.0,
    },
    isFeatured: true,
    isBestSeller: true,
    stockQuantity: 60,
  },
  {
    name: "Organic Ashwagandha Root Powder (Nagbala Grade)",
    slug: "organic-ashwagandha-root-powder",
    category: "powders",
    tagline: "Pure Withania somnifera roots for deep relaxation",
    ritualInstruction: "Stir half a spoon into warm milk before sleep.",
    price: 380,
    compareAtPrice: 480,
    weightGrams: 200,
    sku: "NR-ASH-200",
    description: "Pure Withania somnifera roots meticulously pounded to preserve active withanolides for deep restorative rest and HPA axis support.",
    images: ["https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Nagaur Cluster",
      region: "Thar Border",
      state: "Rajasthan",
    },
    harvestPeriod: "February 2026",
    labReportRef: "NR-LAB-ASHW-312",
    ritualTiming: "Night",
    benefits: ["HPA Axis Support", "Restorative Sleep", "Adaptogenic"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 245,
      protein: 3.9,
      carbohydrates: 49.9,
      dietaryFiber: 24.2,
      fat: 0.3,
    },
    isFeatured: false,
    isBestSeller: true,
    stockQuantity: 110,
  },
  {
    name: "Raw Sun-Dried Pumpkin Seeds (Pepitas)",
    slug: "raw-sun-dried-pumpkin-seeds",
    category: "seeds",
    tagline: "Heirloom magnesium-rich raw pepita seeds",
    ritualInstruction: "A small katori as an afternoon snack instead of processed biscuits.",
    price: 320,
    compareAtPrice: 400,
    weightGrams: 250,
    sku: "NR-PUMP-250",
    description: "Plump, unroasted heirloom pumpkin seeds packed with natural magnesium, zinc, and plant-based protein for afternoon snacking.",
    images: ["https://images.unsplash.com/photo-1567306226416-28f0efdc884f?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Punjab Alluvial Plains",
      region: "Indus Basin",
      state: "Punjab",
    },
    harvestPeriod: "March 2026",
    labReportRef: "NR-LAB-PUMP-518",
    ritualTiming: "Afternoon",
    benefits: ["Magnesium Rich", "Plant Protein", "Zinc Boost"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 559,
      protein: 30.2,
      carbohydrates: 10.7,
      dietaryFiber: 6.0,
      fat: 49.0,
    },
    isFeatured: false,
    isBestSeller: true,
    stockQuantity: 140,
  },
  {
    name: "Cold-Pressed Black Sesame Seed Oil",
    slug: "cold-pressed-black-sesame-seed-oil",
    category: "pantry",
    tagline: "Traditional wooden churner extracted black sesame oil",
    ritualInstruction: "Ideal for culinary tempering or traditional body massage.",
    price: 499,
    compareAtPrice: 599,
    weightGrams: 500,
    sku: "NR-OIL-500",
    description: "Traditional wooden churner (Kachi Ghani) extracted black sesame oil, rich in sesamol and essential fatty acids for culinary and Abhyanga rituals.",
    images: ["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Saurashtra Cluster",
      region: "Kathiawar Peninsula",
      state: "Gujarat",
    },
    harvestPeriod: "January 2026",
    labReportRef: "NR-LAB-OIL-701",
    ritualTiming: "Anytime",
    benefits: ["Kachi Ghani Extracted", "Sesamol Rich", "Abhyanga Ready"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 884,
      protein: 0.0,
      carbohydrates: 0.0,
      dietaryFiber: 0.0,
      fat: 100.0,
    },
    isFeatured: false,
    isBestSeller: false,
    stockQuantity: 50,
  },
  {
    name: "Sprouted Ragi (Finger Millet) Power Malt",
    slug: "sprouted-ragi-power-malt",
    category: "superfoods",
    tagline: "Enzyme-activated calcium-rich sprouted finger millet",
    ritualInstruction: "Whisk into warm water or milk to form a nourishing morning porridge.",
    price: 240,
    compareAtPrice: 300,
    weightGrams: 400,
    sku: "NR-RAGI-400",
    description: "Enzyme-activated sprouted finger millet stone-ground into a fine flour. Naturally abundant in bioavailable calcium and gentle on infant and adult digestion.",
    images: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Mandya District Cooperative",
      region: "Kaveri Basin",
      state: "Karnataka",
    },
    harvestPeriod: "April 2026",
    labReportRef: "NR-LAB-RAGI-811",
    ritualTiming: "Morning",
    benefits: ["Bioavailable Calcium", "Enzyme Activated", "Gentle Digestion"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 328,
      protein: 7.3,
      carbohydrates: 72.0,
      dietaryFiber: 11.5,
      fat: 1.3,
    },
    isFeatured: false,
    isBestSeller: false,
    stockQuantity: 90,
  },
  {
    name: "Himalayan Pink Rock Salt Crystals (Coarse)",
    slug: "himalayan-pink-rock-salt-crystals",
    category: "pantry",
    tagline: "Hand-mined ancient sea salt crystals with trace minerals",
    ritualInstruction: "Grind fresh into daily culinary preparations.",
    price: 199,
    compareAtPrice: 250,
    weightGrams: 500,
    sku: "NR-SALT-500",
    description: "Ancient sea salt deposits hand-mined from the Khewra salt range, untouched by microplastics and rich in 84 essential trace minerals.",
    images: ["https://images.unsplash.com/photo-1518110992383-207d5e4b2d77?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Sub-Himalayan Foothills",
      region: "Shiwalik Range",
      state: "Uttarakhand",
    },
    harvestPeriod: "Permanent Reserve",
    labReportRef: "NR-LAB-SALT-909",
    ritualTiming: "Anytime",
    benefits: ["84 Trace Minerals", "Microplastic Free", "Hand Mined"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 0,
      protein: 0,
      carbohydrates: 0,
      dietaryFiber: 0,
      fat: 0,
    },
    isFeatured: false,
    isBestSeller: false,
    stockQuantity: 200,
  },
  {
    name: "Organic Flaxseed (Alsi) Omega-3 Kernels",
    slug: "organic-flaxseed-omega-3-kernels",
    category: "seeds",
    tagline: "Golden-brown lignan-rich plant omega seeds",
    ritualInstruction: "Lightly roast and sprinkle over salads or consume ground.",
    price: 180,
    compareAtPrice: 230,
    weightGrams: 300,
    sku: "NR-FLAX-300",
    description: "Cleaned, graded golden-brown flax seeds loaded with lignans and high-stability plant omega oils.",
    images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Vidarbha Cluster",
      region: "Central Plateau",
      state: "Maharashtra",
    },
    harvestPeriod: "February 2026",
    labReportRef: "NR-LAB-FLAX-121",
    ritualTiming: "Morning",
    benefits: ["High Lignans", "Plant Omega-3", "Digestive Health"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 534,
      protein: 18.3,
      carbohydrates: 28.9,
      dietaryFiber: 27.3,
      fat: 42.2,
    },
    isFeatured: false,
    isBestSeller: false,
    stockQuantity: 130,
  },
  {
    name: "Pure Brahmi (Gotu Kola) Leaf Powder",
    slug: "pure-brahmi-gotu-kola-leaf-powder",
    category: "powders",
    tagline: "Marshland centella leaves for cerebral clarity",
    ritualInstruction: "Brew into a warm herbal tea infusion.",
    price: 340,
    compareAtPrice: 420,
    weightGrams: 150,
    sku: "NR-BRAH-150",
    description: "Centella asiatica leaves harvested from marshy river valleys, shade-dried to support cognitive clarity and cerebral microcirculation.",
    images: ["https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Kerala Backwater Belt",
      region: "Vembanad Wetland",
      state: "Kerala",
    },
    harvestPeriod: "March 2026",
    labReportRef: "NR-LAB-BRAH-333",
    ritualTiming: "Morning",
    benefits: ["Cerebral Clarity", "Microcirculation", "Nootropic"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 235,
      protein: 4.5,
      carbohydrates: 45.0,
      dietaryFiber: 15.0,
      fat: 1.2,
    },
    isFeatured: false,
    isBestSeller: false,
    stockQuantity: 75,
  },
  {
    name: "Malabar Whole Green Cardamom Pods (Alleppey Extra Bold)",
    slug: "malabar-whole-green-cardamom-pods",
    category: "pantry",
    tagline: "Aromatic high-altitude green cardamom pods",
    ritualInstruction: "Crush one pod into morning chai or desserts.",
    price: 650,
    compareAtPrice: 800,
    weightGrams: 100,
    sku: "NR-CARD-100",
    description: "Aromatic grade-A green cardamom pods possessing high essential oil content, sourced from high-altitude spice estates.",
    images: ["https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Idukki Hills Estate",
      region: "Cardamom Hills",
      state: "Kerala",
    },
    harvestPeriod: "January 2026",
    labReportRef: "NR-LAB-CARD-442",
    ritualTiming: "Morning",
    benefits: ["High Essential Oils", "Digestive Spice", "Grade-A Extra Bold"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 311,
      protein: 10.8,
      carbohydrates: 68.5,
      dietaryFiber: 28.0,
      fat: 6.7,
    },
    isFeatured: false,
    isBestSeller: true,
    stockQuantity: 65,
  },
  {
    name: "Sun-Dried Organic White Quinoa Grain",
    slug: "sun-dried-organic-white-quinoa-grain",
    category: "seeds",
    tagline: "Complete plant protein pseudo-cereal grain",
    ritualInstruction: "Rinse thoroughly and simmer in water for 15 minutes as a grain base.",
    price: 395,
    compareAtPrice: 495,
    weightGrams: 500,
    sku: "NR-QUIN-500",
    description: "Complete plant protein pseudo-cereal cultivated in high-altitude southern Deccan plateaus. Thoroughly washed and saponin-free.",
    images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Deccan Plateau Cooperative",
      region: "Southern Uplands",
      state: "Karnataka",
    },
    harvestPeriod: "February 2026",
    labReportRef: "NR-LAB-QUIN-554",
    ritualTiming: "Afternoon",
    benefits: ["Complete Protein", "Saponin Free", "Low Glycemic"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 368,
      protein: 14.1,
      carbohydrates: 64.2,
      dietaryFiber: 7.0,
      fat: 6.1,
    },
    isFeatured: false,
    isBestSeller: false,
    stockQuantity: 105,
  },
  {
    name: "Traditional Golden Turmeric Root Powder (Lakadong Variety)",
    slug: "traditional-golden-turmeric-root-powder-lakadong",
    category: "superfoods",
    tagline: "High-curcumin heirloom turmeric powder",
    ritualInstruction: "Stir into warm milk with black pepper for golden milk.",
    price: 290,
    compareAtPrice: 360,
    weightGrams: 250,
    sku: "NR-TURM-250",
    description: "High-curcumin (7.8%) heirloom turmeric roots steam-cleaned and milled into a brilliant golden aromatic powder.",
    images: ["https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Jaintia Hills Estate",
      region: "Northeast Plateau",
      state: "Meghalaya",
    },
    harvestPeriod: "January 2026",
    labReportRef: "NR-LAB-TURM-665",
    ritualTiming: "Night",
    benefits: ["7.8% Curcumin", "Anti-Inflammatory", "Heirloom Variety"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 354,
      protein: 7.8,
      carbohydrates: 64.9,
      dietaryFiber: 21.1,
      fat: 9.9,
    },
    isFeatured: false,
    isBestSeller: true,
    stockQuantity: 160,
  },
  {
    name: "Raw Organic Sunflower Seed Kernels",
    slug: "raw-organic-sunflower-seed-kernels",
    category: "seeds",
    tagline: "Shelled Vitamin E-rich raw sunflower kernels",
    ritualInstruction: "Toss into salads or consume raw as a daily snack.",
    price: 220,
    compareAtPrice: 280,
    weightGrams: 250,
    sku: "NR-SUN-250",
    description: "Nutritious shelled sunflower seeds rich in Vitamin E, selenium, and heart-healthy phytosterols.",
    images: ["https://images.unsplash.com/photo-1471193945509-9ad0617afabf?auto=format&fit=crop&w=900&q=80"],
    farmCluster: {
      name: "Karnataka Farmland Cluster",
      region: "Northern Maidan",
      state: "Karnataka",
    },
    harvestPeriod: "March 2026",
    labReportRef: "NR-LAB-SUN-778",
    ritualTiming: "Afternoon",
    benefits: ["Vitamin E Rich", "Selenium Boost", "Phytosterols"],
    nutritionalFacts: {
      servingSize: "100g",
      energyKcal: 584,
      protein: 20.8,
      carbohydrates: 20.0,
      dietaryFiber: 8.6,
      fat: 51.5,
    },
    isFeatured: false,
    isBestSeller: false,
    stockQuantity: 115,
  },
];

async function seedDatabase() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("Connected to MongoDB for Database Seeding...");

    // Seed Journals
    await Journal.deleteMany({});
    console.log("Cleared existing journal collection.");
    const seededJournals = await Journal.insertMany(seedJournals);
    console.log(`Successfully seeded ${seededJournals.length} journal articles.`);

    // Seed Products
    await Product.deleteMany({});
    console.log("Cleared existing product collection.");
    const seededProducts = await Product.insertMany(seedProducts);
    console.log(`Successfully seeded ${seededProducts.length} product items.`);

    console.log("All database seeding completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Error during database seeding:", error);
    process.exit(1);
  }
}

seedDatabase();